### PR TITLE
Structure Refactoring

### PR DESCRIPTION
**Pull request by LukvonStrom**
Used the Structure created by express-generator. Inserted pug/jade as a workaround for the template engine statement that has to be existent.

### CODE REVIEW

**Comment by LukvonStrom** [comment]
Should be using the actual commits now. Are you going to merge this @Sofaklient ?

**Comment by LukvonStrom** [comment]
Btw. Sorry for some weird commit messages, I was expieriencing issues with my local Git.

**Comment by LukvonStrom** [comment]
Because I was forced to use a template engine its possible that you have to improve the error and the standarad template. If you need help just drop me some lines on discord :)

**Comment by Sofaklient** [comment]
Merged.

**Pull request merged**
