### PR TITLE
Add Team List

### PR DESCRIPTION
**Pull request by Ripes**
Add a table with all Developers (**only static**)
http://127.0.0.1:3000/join#team

**Update**
Animate

### CODE REVIEW

**Comment by LukvonStrom** [comment]
Please refix typos.

**Comment by Ripes** [comment]
Where?

**Comment by LukvonStrom** [comment]
All the misstakes in join which I corrected in my last commit were overriten by yours.

**Comment by Ripes** [comment]
done

**Comment by LukvonStrom** [comment]
May you provide a live demo for the wow.js animations?

**Comment by Ripes** [comment]
Yes http://92.222.72.61:3000

**Comment by Sofaklient** [comment]
Logo has no zoom-in effect on home page.

**Pull request closed without merging**
